#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KeySndr.Clients.Mobile.Droid.Resource", IsApplication=true)]

namespace KeySndr.Clients.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int action_button_active_gray = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int action_button_disabled_gray = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int aqua = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int black = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int blue = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int def = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int fuchsia = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int gray = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int green = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int lime = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int maroon = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int navy = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int olive = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int orange = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int purple = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int red = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int silver = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int teal = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int webgreen = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int yellow = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_aspect_ratio_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_cloud_download_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_loop_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_settings_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int action_load_confs = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int action_load_fullscreen = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int action_refresh = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int action_settings = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int enableCache = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int ipEditText = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int ipTextView = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int portEditText = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int portTextView = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int selectConfigurationButtonCancel = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int selectConfigurationButtonOk = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int selectConfigurationSpinner = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int webview = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int intermediate_progress = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int select_configuration_dialog = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Settings = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_activity_actions = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int settings_activity_actions = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int action_create_conf = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int action_load_confs = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int action_load_fullscreen = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int action_refresh = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
